-- BETWEEN

/*
O BETWEEN E USADO PARA ENCONTRAR VALOR ENTRE UM VALOR MININO E VALOR MAXIMO

VALOR BETWEEN MININO AND MAXIMO ;

EH BASICAMENTE A  MESMA COISA QUE DIZER:
VALOR >= MININO AND VALOR <= MAXIMO;
*/
SELECT *
FROM Production.Product
WHERE ListPrice BETWEEN 1000 and 1500;

-- E DA PRA FAZER O INVERSO 

SELECT *
FROM Production.Product
WHERE ListPrice NOT BETWEEN 1000 and 1500;

-- VALORES QUE NAO ESTAO ENTRE 1000 E 1500;

-- PODEMOS FAZER ISSO TBM COM DATAS.

SELECT *
FROM HumanResources.Employee
WHERE HireDate BETWEEN '2009/01/01' AND '2010/01/01'  -- EMPREGADOS QUE FORAM CONTRATADOS ENTRE ESSA DATA

SELECT *
FROM HumanResources.Employee
WHERE HireDate BETWEEN '2009/01/01' AND '2010/01/01'
ORDER BY HireDate                                       -- ADICIONANDO UM ORDER BY PRA FICAR MAIS LEGIVEL E ORDENADO.