-- GROUP BY 

/* O GROUP BY BASICMENTE DIVIDE O RESULTADO DA SUA PESQUISA EM GRUPOS

PARA CADA GRUPO VOCE PODE APLICAR UMA FUNCAO DE AGREGACAO, POR EXEMPLO:
CALCULAR A SOMA DE ITENS 
CONTAR O NUMERO DE ITENS NAQUELE GRUPO */

SELECT coluna1, funcaoAgregacao(coluna2)
FROM nomeTabela
GROUP BY coluna1;

--


SELECT SpecialOfferId, SUM(UnitPrice) AS "SOMA"
FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID

-- VAMOS DIZER QUE EU QUERO SABER QUANTOS CADA PRODUTO FOI VENDIDO ATE HOJE
SELECT ProductID, COUNT(PRODUCTID) as "contagem"
FROM SALES.SalesOrderDetail
GROUP BY ProductId

--VAMOS DIZER QUE QUERO SABER QUANTOS NOMES DE CADA NOME TEMOS CADASTRADOS EM NOSSO BANCO DE DADOS

SELECT FirstName, count(firstname) as "contagem"
FROM PERSON.Person
GROUP BY FirstName
ORDER BY FirstName asc  -- ORDENANDO ALFABETICAMENTE

--NA TABELA PRODUCTIO.PRODUCT QUERO SABER A MEDIA DE PRECO PARA OS PRODUTOS QUE SAO PRATAS(SILVER)

SELECT COLOR, AVG (LISTPRICE)
FROM Production.Product
WHERE COLOR = 'SILVER'
GROUP BY Color


/*DESAFIO 1
EU PRECISO SABER QUANTAS PESSOAS TEM O MESMO MIDDLENAME AGRUPADAS POR O MIDDLENAME*/

SELECT MiddleName, count(MiddleName) as "QUANTIDADE"
FROM Person.Person
GROUP BY MiddleName

/*DESAFIO 2
EU PRECISO SABER EM MEDIA QUAL EH A QUANTIDADE QUE CADA PRODUTO EH VENDIDO NA LOJA*/

SELECT ProductID, AVG(ORDERQTY) AS "MEDIA"
FROM Sales.SalesOrderDetail
GROUP BY ProductID

/*DESAFIO 3
EU QUERO SABER QUAL FORAM AS 10 VENDAS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA (LINETOTAL) POR PRODUTO DO MAIOR VALOR PARA O MENOR*/

SELECT TOP 10 ProductID, SUM(LineTotal)
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY sum(LineTotal) DESC


/*DESAFIO 4
EU PRECISO SABER QUANTOS PRODUTOS E QUAL EH A QUANTIDADE MEDIA DE PRODUTOS QUE TEMOS CADASTRADOS NAS NOSSAS ORDEM DE SERVICO, AGRUPADOS POR PRODUCTID*/

SELECT ProductID, COUNT(PRODUCTID) AS "CONTAGEM", AVG(ORDERQTY) AS MEDIA
FROM Production.WorkOrder
GROUP BY ProductID
