-- LIKE

/*
VAMOS DIZER QUE QUEREMOS ENCONTRAR UMA PESSOA NO BANCO DE DADOS QUE NOS SABEMOS QUE O NOME DELA ERA OVI.. ALGUMA COISA
*/

SELECT *
FROM Person.Person
WHERE FirstName LIKE 'ovi%'  -- PERCENTUAL DEPOIS MOSTRA Q NAO IMPORTA OQ VEM DEPOIS, CASO LEMBRE SO O INICIO

SELECT *
FROM Person.Person
WHERE FirstName LIKE '%to'  -- PERCENTUAL ANTES MOSTRA Q NAO IMPORTA OQ VEM ANTES, CASO LEMBRE SO O FINAL

SELECT *
FROM Person.Person
WHERE FirstName LIKE '%essa%'  -- PERCENTUAL ANTES E DEPOIS MOSTRA Q NAO IMPORTA OQ VEM ANTES E DEPOIS, CASO LEMBRE SO O MEIO

SELECT *
FROM Person.Person
WHERE FirstName LIKE '%ro_' -- SUBSTITUINDO O _ POR ULTIMO CARACTER 