/* DESAFIO 1 

QUANTOS PRODUTOS TEMOS CADASTRADOS NO SISTEMA QUE CUSTAM MAIS QUE 1500 USD? */

SELECT COUNT (*) 
FROM Production.Product
WHERE ListPrice > 1500 -- 39 rows

/* DESAFIO 2 

QUANTAS PESSOAS TEMOS COM O SOBRENOME QUE INICIA COM A LETRA P*/

SELECT COUNT(*)        -- OU COUNT(lastname)
FROM person.person
WHERE LastName LIKE 'P%' --1187 ROW

/* DESAFIO 3 

EM QUANTAS CIDADES UNICAS ESTAO CADASTRADOS NOSSOS CLIENTES */

SELECT COUNT (DISTINCT City)
FROM person.Address -- 575 ROWS 


/* DESAFIO 4
QUAIS SAO AS CIDADES UNICAS QUE TEMOS CADASTADOS EM NOSSO SISTEMA? */

SELECT DISTINCT (city)
FROM PERSON.Address  -- 575 rows

/* DESAFIO 5
QUANTOS PRODUTOS VERMELHOS TEM O PRECO ENTRE 500 E 100 USD? */

SELECT COUNT(*)
FROM Production.Product
WHERE COLOR = 'red' AND ListPrice BETWEEN 500 AND 1000 -- 11 ROWS

/* DESAFIO 6
QUANTOS PRODUTOS CADASTRADOS TEM A PALAVRA 'road' no nome deles?*/

SELECT COUNT(*)
FROM Production.Product
WHERE Name like '%road%' -- 103 ROWS

