-- IN

/*
NOS USAMOS O PERADOR IN JUNTO COM O WHERE

PARA VERIFICAR SE UM VALOR CORRESPONDE COM QUALQUER VALOR PASSADO NA LISTA DE VALORES

valor IN (valor1, valor2)
valor IN (SELECT valor FROM nomeDaTabela) -- ISSO EH CHAMADO DE SUBSELECT OU SUBQUERY
color IN('BLUE', 'RED')

*/

SELECT *
FROM person.Person
WHERE BusinessEntityID IN (2, 7, 13)

-- ISSO EH BOM PQ EH MAIS RAPIDO E TBM SE NAO TERIAMOS QUE FAZER ASSIM
 
SELECT *
FROM person.Person
WHERE BusinessEntityID =2
OR BusinessEntityID = 7
OR BusinessEntityID =1

-- TBM PODEMOS USAR O NOT EM CONJUNTO PARA FUNCIONAR TIPO COMO EXCLUSAO 

SELECT *
FROM person.Person
WHERE BusinessEntityID NOT IN (2, 7, 13)
